[package]
name = "bevy_entropy"
version = "0.9.0"
edition = "2021"
description = "Bevy Engine's RNG integration"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["game", "bevy", "rand", "rng"]
categories = ["game-engines", "algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = { path = "../bevy_app", version = "0.9.0" }
bevy_ecs = { path = "../bevy_ecs", version = "0.9.0" }
bevy_reflect = { path = "../bevy_reflect", version = "0.9.0" }
serde = { version = "1.0", features = ["derive"] }
rand_core = { version = "0.6", features = ["std", "serde1"] }
rand_chacha = { version = "0.3", features = ["serde1"] }

[dev-dependencies]
rand = "0.8"

[target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[[example]]
name = "determinism"
path = "examples/determinism.rs"

[[example]]
name = "parallelism"
path = "examples/parallelism.rs"
