[package]
name = "bevy_entropy"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = { path = "../bevy_app", version = "0.9.0" }
bevy_ecs = { path = "../bevy_ecs", version = "0.9.0" }
bevy_reflect = { path = "../bevy_reflect", version = "0.9.0" }
serde = { version = "1.0", features = ["derive"] }
rand_core = { version = "0.6", features = ["serde1"] }
rand_chacha = { version = "0.3" }
